{% set name = "devscripts" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/devscripts-{{ version }}.tar.gz
  sha256: 0ae7e9eefcd9efda6221c5347e183e77ef7574d82ba39411f5f75d15c20da616

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - devscripts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/massard-t/devscripts
  summary: Scripts and functions to use while coding
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/massard-t/devscripts

extra:
  recipe-maintainers:
    - HeavyTony2
